In [2]:
import pandas as pd

In [3]:
# Read the data

p_2 = pd.read_excel('Credit-Banking-3.xlsx', sheet_name= 'Project_2')

c_info = pd.read_excel('Credit-Banking-3.xlsx', sheet_name= 'Curtomer_Info')

In [9]:
p_2. head(20)

,Credit_card,Product_ID,P_CATEGORY,CONDTION,Brand,Price,Selling_price,Coupon_ID,Date,Time,GTIN,MPN,Merchant_name,M_ID,Payment Method,Transaction ID,Return_ind,Return_date
0,4595.0,534,SHOES,New,RKFCM,1484.74,1471.74,BN710,2014-08-26,17:16:17,3109172,547836726,Peninsula Beauty,YE5901,Prepaid card,30462,0,NaT
1,6679.0,396,LUGGAGE,New,TNVON,1452.50,1442.50,KF815,2014-01-26,15:40:52,7583605,279617132,DODOcase,UW7354,Mobile carrier Billing,37927,0,NaT
2,7075.0,449,SHOES,Refurbished,VKKEA,4308.02,4284.02,UG960,2014-01-03,01:29:05,9985192,633765867,Staples,VN6656,Credit card,80640,0,NaT
3,1418.0,145,BEDDING,New,PIUEM,3272.59,3249.59,DK471,2014-05-30,09:10:00,7720605,734500382,Road Runner Sports,MS6579,Prepaid card,58692,0,NaT
4,6740.0,844,ELECTRONICS,Used,FMBZC,628.67,608.67,OJ311,2014-08-14,05:31:30,8367528,241944637,L'Occitane,GN3944,Debit card,21505,0,NaT
5,4305.0,922,LUGGAGE,New,IWPJG,3788.97,3698.97,NaN,2014-08-18,02:25:07,7436510,436743043,Guitar Center,GN4259,Mobile carrier Billing,75073,0,NaT
6,4477.0,616,OFFICE SUPPLIES,Used,EVWJY,1011.90,1001.90,LU503,2014-04-22,10:04:56,2195580,258635926,Cole Hardware,EX7730,Mobile carrier Billing,89706,0,NaT
7,4672.0,300,APPLIANCES,New,KZDWR,4918.58,4891.58,UX835,2014-01-20,01:45:09,1593030,943939956,Walgreens,VW7191,Credit card,63096,0,NaT
8,5481.0,827,ELECTRONICS,New,OULOW,2830.51,2802.51,KG804,2014-05-12,09:43:54,6339658,532985898,Gymboree,ZF8986,Prepaid card,74652,0,NaT
9,5974.0,470,LUGGAGE,Used,TNVON,4783.25,4764.25,ER876,2014-09-23,05:13:44,4604782,832455526,REI,EI6775,Credit card,28877,1,2014-09-30
10,NaN,266,COMPUTERS,Used,GCVNE,2143.08,2098.08,MS262,2014-07-03,17:23:52,8417362,243355173,REI,EI6774,Credit card,74588,0,NaT
11,3705.0,236,ELECTRONICS,Used,BEFJD,4195.69,4172.69,SZ440,2014-08-02,07:34:13,7532423,594165749,Ulta,UO9658,Credit card,67276,0,NaT
12,6391.0,694,BABY CLOTHING,Used,GOZLI,3967.19,3918.19,GX363,2014-02-17,12:35:33,9712740,237169507,The North Face,GH6872,Mobile carrier Billing,99538,0,NaT
13,8844.0,832,DECOR,New,ZACKV,1023.49,974.49,SZ707,2014-07-26,00:00:17,6544166,696803356,Costco,GW8247,Debit card,90940,0,NaT
14,1256.0,722,GAMES,Refurbished,EITXF,2421.99,2383.99,HQ715,2014-11-12,16:56:51,7084452,882578141,Peninsula Beauty,YE5901,Mobile carrier Billing,82394,0,NaT
15,NaN,710,KITCHEN & DINING,New,RGMIK,663.82,650.82,ZG209,2014-04-26,17:41:01,8042908,596308320,Road Runner Sports,MS6579,Mobile carrier Billing,15559,0,NaT
16,3833.0,763,DECOR,Refurbished,LBVIW,4943.44,4943.44,MD699,2014-06-27,07:01:54,5427529,673782264,Right Start,IQ1509,Mobile carrier Billing,37012,0,NaT
17,6565.0,396,LUGGAGE,New,TNVON,1452.50,1439.50,FU406,2014-03-24,17:02:19,6595702,714268927,DODOcase,UW7354,Mobile carrier Billing,26010,0,NaT
18,4852.0,136,KITCHEN & DINING,New,NSILF,4019.79,3984.79,OY795,2014-02-21,06:45:11,2593122,512087228,Nine West,RM9837,Credit card,14148,0,NaT
19,4139.0,295,COMPUTERS,New,YEJZI,2868.97,2827.97,XU183,2014-11-05,16:52:32,5374063,403676957,DFLOWERS,ZG2587,Credit card,31465,0,NaT

In [4]:
c_info.head(50)

,C_ID,Email,Name,Mobile_number,Gender,Age,City,State,Address
0,3768,eddie@yahoomail.com,EDDIE,9045258449,M,83,Louisville,Kentucky,Masked
1,4852,rose@hotmail.com,ROSE,8834789103,F,87,Kansas City,Missouri,Masked
2,1174,amy@yahoomail.com,AMY,9557690013,F,31,Seattle,Washington,Masked
3,4807,clarence@gmail.com,CLARENCE,9394398429,M,37,Seattle,Washington,Masked
4,9131,johnny@hotmail.com,JOHNNY,9976623538,F,80,Columbus,Ohio,Masked
5,3496,clifford@yahoomail.com,CLIFFORD,9591889392,M,35,Seattle,Washington,Masked
6,8523,kathleen@hotmail.com,KATHLEEN,9790455985,F,34,Seattle,Washington,Masked
7,3122,carol@gmail.com,CAROL,9400471658,F,90,San Diego,California,Masked
8,7001,teresa@hotmail.com,TERESA,8813425988,F,72,Phoenix,Arizona,Masked
9,2637,ann@hotmail.com,ANN,9506618471,M,65,Louisville,Kentucky,Masked
10,4477,gloria@yahoomail.com,GLORIA,8868782850,F,51,Austin,Texas,Masked
11,9896,troy@yahoomail.com,TROY,9197303171,M,39,Kansas City,Missouri,Masked
12,6324,debra@yahoomail.com,DEBRA,9586531200,F,34,Austin,Texas,Masked
13,4691,greg@hotmail.com,GREG,9415221034,M,43,Los Angeles,California,Masked
14,8067,katherine@yahoomail.com,KATHERINE,9470251219,F,76,Houston,Texas,Masked
15,9629,sean@yahoomail.com,SEAN,8937472140,F,25,Boston,Massachusetts,Masked
16,1418,miguel@gmail.com,MIGUEL,8883936622,M,35,Louisville,Kentucky,Masked
17,3598,judy@hotmail.com,JUDY,9252952579,F,62,San Francisco,California,Masked
18,3050,tim@yahoomail.com,TIM,9367894695,M,21,San Francisco,California,Masked
19,4595,andrea@yahoomail.com,ANDREA,9467152868,M,68,Boston,Massachusetts,Masked
20,1831,frederick@hotmail.com,FREDERICK,9889212726,M,42,Los Angeles,California,Masked
21,5432,kathryn@hotmail.com,KATHRYN,9107663641,F,91,Houston,Texas,Masked
22,6814,derek@hotmail.com,DEREK,9620684538,M,81,Dallas,Texas,Masked
23,8705,wanda@yahoomail.com,WANDA,8894834459,F,85,San Jose,California,Masked
24,2866,judy@hotmail.com,JUDY,8857290019,M,70,Kansas City,Missouri,Masked
25,3833,evelyn@yahoomail.com,EVELYN,8993254026,F,50,San Francisco,California,Masked
26,9137,bonnie@yahoomail.com,BONNIE,9987552390,F,26,San Jose,California,Masked
27,9554,pamela@yahoomail.com,PAMELA,9400916962,F,19,Los Angeles,California,Masked
28,7173,marie@hotmail.com,MARIE,9936858051,F,18,Kansas City,Missouri,Masked
29,2804,theresa@hotmail.com,THERESA,9168629885,M,87,Dallas,Texas,Masked
30,3402,sharon@yahoomail.com,SHARON,9344463431,F,27,Boston,Massachusetts,Masked
31,5008,catherine@yahoomail.com,CATHERINE,9664987247,F,70,Houston,Texas,Masked
32,6946,barry@hotmail.com,BARRY,9076928040,M,52,Dallas,Texas,Masked
33,8639,beverly@yahoomail.com,BEVERLY,9446943344,F,68,Houston,Texas,Masked
34,2297,kathy@hotmail.com,KATHY,9662329307,F,70,Seattle,Washington,Masked
35,9210,anne@hotmail.com,ANNE,9787873200,F,95,Boston,Massachusetts,Masked
36,3018,jay@yahoomail.com,JAY,8962186751,M,95,Los Angeles,California,Masked
37,4879,diana@hotmail.com,DIANA,9203141494,F,47,Louisville,Kentucky,Masked
38,9063,alan@gmail.com,ALAN,9983135834,F,15,Dallas,Texas,Masked
39,3500,cheryl@hotmail.com,CHERYL,8881689041,F,73,Seattle,Washington,Masked
40,8197,ricky@hotmail.com,RICKY,9816899344,M,31,San Jose,California,Masked
41,3931,sara@hotmail.com,SARA,9350096089,F,24,Austin,Texas,Masked
42,9725,kathryn@yahoomail.com,KATHRYN,9473775302,M,32,San Francisco,California,Masked
43,9305,betty@yahoomail.com,BETTY,9676448074,F,59,Las Vegas,Nevada,Masked
44,4284,alice@gmail.com,ALICE,9900207513,M,85,San Francisco,California,Masked
45,7481,janet@yahoomail.com,JANET,8865424168,F,80,Los Angeles,California,Masked
46,2535,edwin@hotmail.com,EDWIN,8956487701,M,77,Austin,Texas,Masked
47,7433,ashley@gmail.com,ASHLEY,9160754102,F,76,Louisville,Kentucky,Masked
48,3175,christine@hotmail.com,CHRISTINE,9445080762,F,17,San Jose,California,Masked
49,7210,mario@hotmail.com,MARIO,9938552460,M,84,San Jose,California,Masked

In [5]:
#Fixing the Age values which are less than 18
def replace_age_less_than_18(df):
    # Calculate the average age of entries where age is greater than or equal to 18
    average_age = df[df['Age'] >= 18]['Age'].mean()
    # Replace ages less than 18 with the average age
    df.loc[df['Age'] < 18, 'Age'] = average_age
    return df

In [7]:
c_info_no18= replace_age_less_than_18(c_info)

# Display the first few rows of the updated 'c_info' DataFrame
print("Updated Customer_Info DataFrame:")
c_info_no18.head(50)

Updated Customer_Info DataFrame:

,C_ID,Email,Name,Mobile_number,Gender,Age,City,State,Address
0,3768,eddie@yahoomail.com,EDDIE,9045258449,M,83.000000,Louisville,Kentucky,Masked
1,4852,rose@hotmail.com,ROSE,8834789103,F,87.000000,Kansas City,Missouri,Masked
2,1174,amy@yahoomail.com,AMY,9557690013,F,31.000000,Seattle,Washington,Masked
3,4807,clarence@gmail.com,CLARENCE,9394398429,M,37.000000,Seattle,Washington,Masked
4,9131,johnny@hotmail.com,JOHNNY,9976623538,F,80.000000,Columbus,Ohio,Masked
5,3496,clifford@yahoomail.com,CLIFFORD,9591889392,M,35.000000,Seattle,Washington,Masked
6,8523,kathleen@hotmail.com,KATHLEEN,9790455985,F,34.000000,Seattle,Washington,Masked
7,3122,carol@gmail.com,CAROL,9400471658,F,90.000000,San Diego,California,Masked
8,7001,teresa@hotmail.com,TERESA,8813425988,F,72.000000,Phoenix,Arizona,Masked
9,2637,ann@hotmail.com,ANN,9506618471,M,65.000000,Louisville,Kentucky,Masked
10,4477,gloria@yahoomail.com,GLORIA,8868782850,F,51.000000,Austin,Texas,Masked
11,9896,troy@yahoomail.com,TROY,9197303171,M,39.000000,Kansas City,Missouri,Masked
12,6324,debra@yahoomail.com,DEBRA,9586531200,F,34.000000,Austin,Texas,Masked
13,4691,greg@hotmail.com,GREG,9415221034,M,43.000000,Los Angeles,California,Masked
14,8067,katherine@yahoomail.com,KATHERINE,9470251219,F,76.000000,Houston,Texas,Masked
15,9629,sean@yahoomail.com,SEAN,8937472140,F,25.000000,Boston,Massachusetts,Masked
16,1418,miguel@gmail.com,MIGUEL,8883936622,M,35.000000,Louisville,Kentucky,Masked
17,3598,judy@hotmail.com,JUDY,9252952579,F,62.000000,San Francisco,California,Masked
18,3050,tim@yahoomail.com,TIM,9367894695,M,21.000000,San Francisco,California,Masked
19,4595,andrea@yahoomail.com,ANDREA,9467152868,M,68.000000,Boston,Massachusetts,Masked
20,1831,frederick@hotmail.com,FREDERICK,9889212726,M,42.000000,Los Angeles,California,Masked
21,5432,kathryn@hotmail.com,KATHRYN,9107663641,F,91.000000,Houston,Texas,Masked
22,6814,derek@hotmail.com,DEREK,9620684538,M,81.000000,Dallas,Texas,Masked
23,8705,wanda@yahoomail.com,WANDA,8894834459,F,85.000000,San Jose,California,Masked
24,2866,judy@hotmail.com,JUDY,8857290019,M,70.000000,Kansas City,Missouri,Masked
25,3833,evelyn@yahoomail.com,EVELYN,8993254026,F,50.000000,San Francisco,California,Masked
26,9137,bonnie@yahoomail.com,BONNIE,9987552390,F,26.000000,San Jose,California,Masked
27,9554,pamela@yahoomail.com,PAMELA,9400916962,F,19.000000,Los Angeles,California,Masked
28,7173,marie@hotmail.com,MARIE,9936858051,F,18.000000,Kansas City,Missouri,Masked
29,2804,theresa@hotmail.com,THERESA,9168629885,M,87.000000,Dallas,Texas,Masked
30,3402,sharon@yahoomail.com,SHARON,9344463431,F,27.000000,Boston,Massachusetts,Masked
31,5008,catherine@yahoomail.com,CATHERINE,9664987247,F,70.000000,Houston,Texas,Masked
32,6946,barry@hotmail.com,BARRY,9076928040,M,52.000000,Dallas,Texas,Masked
33,8639,beverly@yahoomail.com,BEVERLY,9446943344,F,68.000000,Houston,Texas,Masked
34,2297,kathy@hotmail.com,KATHY,9662329307,F,70.000000,Seattle,Washington,Masked
35,9210,anne@hotmail.com,ANNE,9787873200,F,95.000000,Boston,Massachusetts,Masked
36,3018,jay@yahoomail.com,JAY,8962186751,M,95.000000,Los Angeles,California,Masked
37,4879,diana@hotmail.com,DIANA,9203141494,F,47.000000,Louisville,Kentucky,Masked
38,9063,alan@gmail.com,ALAN,9983135834,F,60.197861,Dallas,Texas,Masked
39,3500,cheryl@hotmail.com,CHERYL,8881689041,F,73.000000,Seattle,Washington,Masked
40,8197,ricky@hotmail.com,RICKY,9816899344,M,31.000000,San Jose,California,Masked
41,3931,sara@hotmail.com,SARA,9350096089,F,24.000000,Austin,Texas,Masked
42,9725,kathryn@yahoomail.com,KATHRYN,9473775302,M,32.000000,San Francisco,California,Masked
43,9305,betty@yahoomail.com,BETTY,9676448074,F,59.000000,Las Vegas,Nevada,Masked
44,4284,alice@gmail.com,ALICE,9900207513,M,85.000000,San Francisco,California,Masked
45,7481,janet@yahoomail.com,JANET,8865424168,F,80.000000,Los Angeles,California,Masked
46,2535,edwin@hotmail.com,EDWIN,8956487701,M,77.000000,Austin,Texas,Masked
47,7433,ashley@gmail.com,ASHLEY,9160754102,F,76.000000,Louisville,Kentucky,Masked
48,3175,christine@hotmail.com,CHRISTINE,9445080762,F,60.197861,San Jose,California,Masked
49,7210,mario@hotmail.com,MARIO,9938552460,M,84.000000,San Jose,California,Masked

In [9]:
total_entries = p_2.shape[0]

# Count number of unique entries in each column
unique_entries = p_2['Transaction ID'].nunique()

# Print the results
print("Total number of entries in p_2:", total_entries)
print("\nNumber of unique entries in each column:")
print(unique_entries)

Total number of entries in p_2: 9999

Number of unique entries in each column:
1419